Repository 9oormthon-univ/2025_SEASONTHON_TEAM_82_BE, pull requests merged in 2025-09, with the labels that each got.

#7 [Feature #6] Entity 작성 및 Enum 작성
  build.gradle
  src/main/java/com/bridgeon/app/domain/attachment/entity/Attachment.java
  src/main/java/com/bridgeon/app/domain/board/entity/EmployBoard.java
  src/main/java/com/bridgeon/app/domain/board/entity/EmployScrap.java
  src/main/java/com/bridgeon/app/domain/board/entity/FreeBoard.java
  src/main/java/com/bridgeon/app/domain/board/entity/FreeScrap.java
  src/main/java/com/bridgeon/app/domain/chat/entity/Chat.java
  src/main/java/com/bridgeon/app/domain/info/entity/Banner.java
  src/main/java/com/bridgeon/app/domain/info/entity/FoundationInfo.java
  src/main/java/com/bridgeon/app/domain/user/entity/BusinessPlan.java
  src/main/java/com/bridgeon/app/domain/user/entity/Portfolio.java
  src/main/java/com/bridgeon/app/domain/user/entity/ReadAuthorization.java
  src/main/java/com/bridgeon/app/domain/user/entity/User.java
  src/main/java/com/bridgeon/app/global/dto/json/businessplan/Content.java
  src/main/java/com/bridgeon/app/global/entity/BaseEntity.java
  src/main/java/com/bridgeon/app/global/enums/attachment/MimeType.java
  src/main/java/com/bridgeon/app/global/enums/attachment/TargetType.java
  src/main/java/com/bridgeon/app/global/enums/portfolio/Visibility.java
  src/main/java/com/bridgeon/app/global/enums/user/InterestField.java
  src/main/java/com/bridgeon/app/global/enums/user/Provider.java
  src/main/java/com/bridgeon/app/global/enums/user/Region.java
  src/main/java/com/bridgeon/app/global/enums/user/Role.java
Labels: ✨ Feature

#13 [Feature #5] 카카오 소셜 로그인 구현
  build.gradle
  src/main/java/com/bridgeon/app/AppApplication.java
  src/main/java/com/bridgeon/app/domain/user/controller/AuthController.java
  src/main/java/com/bridgeon/app/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/bridgeon/app/domain/user/repository/UserRepository.java
  src/main/java/com/bridgeon/app/domain/user/service/AuthService.java
  src/main/java/com/bridgeon/app/domain/user/usecase/AuthUseCase.java
  src/main/java/com/bridgeon/app/global/dto/auth/AuthInfo.java
  src/main/java/com/bridgeon/app/global/exception/error/AuthErrorCode.java
  src/main/java/com/bridgeon/app/global/jwt/config/JwtConfig.java
  src/main/java/com/bridgeon/app/global/jwt/handler/AbstractSecurityFailureHandler.java
  src/main/java/com/bridgeon/app/global/jwt/handler/AuthenticationFailureHandler.java
  src/main/java/com/bridgeon/app/global/jwt/handler/AuthorizationFailureHandler.java
  src/main/java/com/bridgeon/app/global/jwt/properties/JwtProperties.java
  src/main/java/com/bridgeon/app/global/jwt/service/AccessTokenGenerateService.java
  src/main/java/com/bridgeon/app/global/jwt/service/RefreshTokenGenerateService.java
  src/main/java/com/bridgeon/app/global/jwt/usecase/TokenGenerateUseCase.java
  src/main/java/com/bridgeon/app/global/jwt/utils/JwtFilter.java
  src/main/java/com/bridgeon/app/global/jwt/utils/JwtUtils.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/client/KakaoOAuthClient.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/dto/KakaoTokenResponseDto.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/dto/KakaoUserResponseDto.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/properties/KakaoOAuthProperties.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/properties/KakaoProviderProperties.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/service/KakaoLoginService.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/usecase/KakaoLoginUseCase.java
  src/main/java/com/bridgeon/app/global/security/config/SecurityConfig.java
  src/main/java/com/bridgeon/app/global/web/config/CorsConfig.java
  src/main/java/com/bridgeon/app/global/web/config/HttpClientConfig.java
  src/main/java/com/bridgeon/app/global/web/utils/CookieUtils.java
  src/test/java/com/bridgeon/app/auth/AuthTest.java
Labels: ✨ Feature

#14 [Feature #12] 자유게시판 상세 글 조회 기능 구현
  src/main/java/com/bridgeon/app/domain/board/controller/GetFreeDetailController.java
  src/main/java/com/bridgeon/app/domain/board/dto/response/FreeDetailResponseDto.java
  src/main/java/com/bridgeon/app/domain/board/repositroy/FreeBoardJpaRepository.java
  src/main/java/com/bridgeon/app/domain/board/service/FreeDetailService.java
  src/main/java/com/bridgeon/app/domain/board/usecase/GetFreeDetailUseCase.java
  src/main/java/com/bridgeon/app/global/exception/error/FreeErrorCode.java
Labels: ✨ Feature

#21 [ Feature #20 ] 창업정보 조회 로직 작성
  src/main/java/com/bridgeon/app/domain/info/controller/GetFoundationInfoListController.java
  src/main/java/com/bridgeon/app/domain/info/dto/response/FoundationInfoItemResponseDto.java
  src/main/java/com/bridgeon/app/domain/info/entity/FoundationInfo.java
  src/main/java/com/bridgeon/app/domain/info/repository/FoundationInfoJpaRepository.java
  src/main/java/com/bridgeon/app/domain/info/service/FoundationInfoListService.java
  src/main/java/com/bridgeon/app/domain/info/usecase/FoundationInfoListUseCase.java
  src/main/java/com/bridgeon/app/global/exception/error/InfoErrorCode.java
Labels: ✨ Feature

#25 [ Fix #24 ] 창업 정보 목록 기능에 이미지URL 추가
  src/main/java/com/bridgeon/app/domain/info/dto/response/FoundationInfoItemResponseDto.java
  src/main/java/com/bridgeon/app/domain/info/dto/response/FoundationInfoRecommendResponseDto.java
  src/main/java/com/bridgeon/app/domain/info/entity/FoundationInfo.java
Labels: 🔨 Fix

#27 [ Feature #26 ] 열람 신청하기
  src/main/java/com/bridgeon/app/domain/board/controller/EmployApplicationController.java
  src/main/java/com/bridgeon/app/domain/board/entity/EmployApplication.java
  src/main/java/com/bridgeon/app/domain/board/repository/EmployApplicationJpaRepository.java
  src/main/java/com/bridgeon/app/domain/board/service/EmployApplicationServiceImpl.java
  src/main/java/com/bridgeon/app/domain/board/usecase/EmployApplicationUseCase.java
  src/main/java/com/bridgeon/app/global/enums/board/ApplyStatus.java
  src/main/java/com/bridgeon/app/global/exception/error/EmployErrorCode.java
Labels: ✨ Feature

#33 [ Feature #32 ] 받은 지원 목록, 요청한 지원 목록 조회
  src/main/java/com/bridgeon/app/domain/board/controller/GetReceivedApplicationController.java
  src/main/java/com/bridgeon/app/domain/board/controller/GetSentApplicationController.java
  src/main/java/com/bridgeon/app/domain/board/dto/response/ReceivedApplicationItemResponseDto.java
  src/main/java/com/bridgeon/app/domain/board/dto/response/SentApplicationItemResponseDto.java
  src/main/java/com/bridgeon/app/domain/board/service/ReceivedApplicationService.java
  src/main/java/com/bridgeon/app/domain/board/service/SentApplicationService.java
  src/main/java/com/bridgeon/app/domain/board/usecase/GetReceivedApplicationsUseCase.java
  src/main/java/com/bridgeon/app/domain/board/usecase/GetSentApplicationsUseCase.java
Labels: ✨ Feature

#41 [Setting] 배포 테스트 - 카카오 로그인 수정
  src/main/java/com/bridgeon/app/domain/user/controller/AuthController.java
Labels: 🌐 Deploy, 🔨 Fix

#44 [Deploy] favicon 해결 후 재배포
  src/main/resources/static/favicon.ico
Labels: 🌐 Deploy

#45 [Fix] "favicon 404 오류 임시 재시도
  src/main/java/com/bridgeon/app/global/jwt/utils/JwtFilter.java
  src/main/java/com/bridgeon/app/global/web/controller/FaviconController.java
Labels: 🔨 Fix

#48 [Deploy] Github Actions 관련 오류 수정 후 배포 테스트
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/java/com/bridgeon/app/domain/user/controller/AuthController.java
Labels: 🌐 Deploy

#49 [Fix:] GitHub Actions 오류 수정
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: 🔨 Fix

#50 [Deploy] GitHub Actions 오류 수정 후 테스트
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: 🌐 Deploy

#51 [ Feature # 40 ] 구인게시판 비즈니스 계획서 연결
  src/main/java/com/bridgeon/app/domain/board/dto/response/EmployPostItemResponseDto.java
  src/main/java/com/bridgeon/app/domain/board/repository/ReadAuthorizationJpaRepository.java
  src/main/java/com/bridgeon/app/domain/board/service/EmployDetailService.java
  src/main/java/com/bridgeon/app/domain/board/service/EmployPostService.java
  src/main/java/com/bridgeon/app/domain/board/service/ReadAuthorizationService.java
  src/main/java/com/bridgeon/app/domain/board/usecase/CheckReadPermissionUseCase.java
  src/main/java/com/bridgeon/app/domain/board/usecase/ReadAuthorizationUseCase.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/BusinessPlanDetailResponseDto.java
Labels: ✨ Feature

#56 [Deploy] GitHub Actions 오류 수정
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: 🌐 Deploy

#57 [ Feature #19 ] 게시판- 첨부파일 / 프로필 - 첨부파일 연동
  src/main/java/com/bridgeon/app/domain/attachment/dto/response/AttachmentResponseDto.java
  src/main/java/com/bridgeon/app/domain/attachment/entity/Attachment.java
  src/main/java/com/bridgeon/app/domain/attachment/repository/AttachmentJpaRepository.java
  src/main/java/com/bridgeon/app/domain/board/dto/response/EmployPostItemResponseDto.java
  src/main/java/com/bridgeon/app/domain/board/dto/response/FreeDetailResponseDto.java
  src/main/java/com/bridgeon/app/domain/board/service/EmployDetailService.java
  src/main/java/com/bridgeon/app/domain/board/service/FreeDetailService.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/ApplicantProfileResponseDto.java
  src/main/java/com/bridgeon/app/domain/user/service/ApplicantDetailService.java
Labels: ✨ Feature

#61 [Fix] 로그인 응답 방식 수정
  .gitignore
  src/main/java/com/bridgeon/app/domain/user/controller/AuthController.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/LoginResponseDto.java
Labels: 🔨 Fix

#63 [Fix] 로그인 응답 방식 수정
  src/main/java/com/bridgeon/app/domain/user/controller/AuthController.java
Labels: 🔨 Fix

#66 [ Feature #58 ] 네이버 뉴스 크롤링 & 트렌드 리포트 API
  src/main/java/com/bridgeon/app/domain/news/controller/TrendController.java
  src/main/java/com/bridgeon/app/domain/news/dto/response/CategorySummaryResponseDto.java
  src/main/java/com/bridgeon/app/domain/news/dto/response/HomeReportResponseDto.java
  src/main/java/com/bridgeon/app/domain/news/dto/response/NewsArticleItemResponseDto.java
  src/main/java/com/bridgeon/app/domain/news/entity/NewsArticle.java
  src/main/java/com/bridgeon/app/domain/news/repository/NewsArticleRepository.java
  src/main/java/com/bridgeon/app/domain/news/service/ArticleListService.java
  src/main/java/com/bridgeon/app/domain/news/service/CategorySummaryService.java
  src/main/java/com/bridgeon/app/domain/news/service/CrawlService.java
  src/main/java/com/bridgeon/app/domain/news/service/HomeReportService.java
  src/main/java/com/bridgeon/app/domain/news/service/KeywordService.java
  src/main/java/com/bridgeon/app/global/naver/config/TrendQueryProperties.java
  src/main/resources/application.yml
Labels: ✨ Feature

#68 [Feature #65] 사용자 정보 관련 API 작성
  src/main/java/com/bridgeon/app/domain/user/controller/PortfolioController.java
  src/main/java/com/bridgeon/app/domain/user/controller/UserController.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/MyPageResponseDto.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/PortfolioDetailResponseDto.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/PortfolioItemDto.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/PortfolioListResponseDto.java
  src/main/java/com/bridgeon/app/domain/user/entity/Portfolio.java
  src/main/java/com/bridgeon/app/domain/user/repository/PortfolioJpaRepository.java
  src/main/java/com/bridgeon/app/domain/user/repository/UserRepository.java
  src/main/java/com/bridgeon/app/domain/user/service/PortfolioService.java
  src/main/java/com/bridgeon/app/domain/user/service/UserService.java
  src/main/java/com/bridgeon/app/domain/user/usecase/PortfolioUseCase.java
  src/main/java/com/bridgeon/app/domain/user/usecase/UserUseCase.java
  src/main/java/com/bridgeon/app/global/exception/error/AuthErrorCode.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/client/KakaoOAuthClient.java
  src/test/java/com/bridgeon/app/auth/AuthTest.java
Labels: ✨ Feature

#69 [Deploy] 2차 스프린트 중간 배포
  src/main/java/com/bridgeon/app/domain/news/controller/TrendController.java
  src/main/java/com/bridgeon/app/domain/news/dto/response/CategorySummaryResponseDto.java
  src/main/java/com/bridgeon/app/domain/news/dto/response/HomeReportResponseDto.java
  src/main/java/com/bridgeon/app/domain/news/dto/response/NewsArticleItemResponseDto.java
  src/main/java/com/bridgeon/app/domain/news/entity/NewsArticle.java
  src/main/java/com/bridgeon/app/domain/news/repository/NewsArticleRepository.java
  src/main/java/com/bridgeon/app/domain/news/service/ArticleListService.java
  src/main/java/com/bridgeon/app/domain/news/service/CategorySummaryService.java
  src/main/java/com/bridgeon/app/domain/news/service/CrawlService.java
  src/main/java/com/bridgeon/app/domain/news/service/HomeReportService.java
  src/main/java/com/bridgeon/app/domain/news/service/KeywordService.java
  src/main/java/com/bridgeon/app/domain/user/controller/PortfolioController.java
  src/main/java/com/bridgeon/app/domain/user/controller/UserController.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/MyPageResponseDto.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/PortfolioDetailResponseDto.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/PortfolioItemDto.java
  src/main/java/com/bridgeon/app/domain/user/dto/response/PortfolioListResponseDto.java
  src/main/java/com/bridgeon/app/domain/user/entity/Portfolio.java
  src/main/java/com/bridgeon/app/domain/user/repository/PortfolioJpaRepository.java
  src/main/java/com/bridgeon/app/domain/user/repository/UserRepository.java
  src/main/java/com/bridgeon/app/domain/user/service/PortfolioService.java
  src/main/java/com/bridgeon/app/domain/user/service/UserService.java
  src/main/java/com/bridgeon/app/domain/user/usecase/PortfolioUseCase.java
  src/main/java/com/bridgeon/app/domain/user/usecase/UserUseCase.java
  src/main/java/com/bridgeon/app/global/exception/error/AuthErrorCode.java
  src/main/java/com/bridgeon/app/global/naver/config/TrendQueryProperties.java
  src/main/java/com/bridgeon/app/global/oauth2/kakao/client/KakaoOAuthClient.java
  src/main/resources/application.yml
  src/test/java/com/bridgeon/app/auth/AuthTest.java
Labels: 🌐 Deploy
